spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false       # Optional, useful for debugging
    eviction-interval-timer-in-ms: 30000  # Optional, controls eviction rate

  logging:
    level:
      com.netflix.eureka: DEBUG           # Optional, useful for debugging

