version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - microservices-kafka-docker
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  eureka-server:
    build: ./eureka-server
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-kafka-docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    build: ./api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - order-api
      - payment-api
      - notification-api
      - inventory-api
      - eureka-server
    networks:
      - microservices-kafka-docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER=http://eureka-server:8761/eureka

  order-api:
    build: ./order-api
    container_name: order-api
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - microservices-kafka-docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kafka_order_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin


  payment-api:
    build: ./payment-api
    container_name: payment-api
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - order-api
    networks:
      - microservices-kafka-docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kafka_payments_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  notification-api:
    build: ./notification-api
    container_name: notification-api
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - microservices-kafka-docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER=http://eureka-server:8761/eureka

  inventory-api:
    build: ./inventory-api
    container_name: inventory-api
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      - microservices-kafka-docker
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kafka_inventory_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

networks:
  microservices-kafka-docker:
    driver: bridge
