server:
  port: 8083
spring:
  application:
    name: notification-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
kafka:
  bootstrap-servers: localhost:9092
  topic:
    payment-result: payment-result-topic
