server:
  port: 8083

spring:
  profiles:
    active: docker
  application:
    name: notification-api
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  application:
    name: notification-api