server:
  port: 8083
spring:
  application:
    name: notification-service

  kafka:
    consumer:
      group-id: notification-service

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true

