server:
  port: 8084
spring:
  application:
    name: inventory-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/kafka_inventory_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    consumer:
      group-id: inventory-service
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
#
#kafka:
#  bootstrap-servers: localhost:9092
#  topic:
#    stock-update: stock-update-topic

