server:
  port: 8082
spring:
  profiles:
    active: docker
  application:
    name: payment-api

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://mysql-db:3306/kafka_payment_db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: payment-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  application:
    name: payment-api
