server:
  port: 8082
spring:
  application:
    name: payment-service

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/kafka_payment_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    consumer:
      group-id: payment-service

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: order-service:${server.port}
      prefer-ip-address: false
      hostname: localhost
