server:
  port: 8081

spring:
  profiles:
    active: docker
  application:
    name: order-api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://mysql-db:3306/kafka_order_db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  application:
    name: order-api

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

resilience4j.ratelimiter:
  instances:
    orderRateLimiter:
      limit-for-period: 1000   # Maximum requests allowed per refresh period
      limit-refresh-period: 1s # Refresh period (1 second)
      timeout-duration: 0      # If limit is exceeded, do not wait (return immediately)

